version: "3.9"
services:
  flask_labeler:
    build:
      context: backend
      dockerfile: LabelerDockerfile
    container_name: mlcheap-labeler
    restart: always
    environment:
      FRONT_URL: "https://skillLab.mlcheap.com"
      APP_ENV: "prod"
      APP_DEBUG: "False"
      MONGO_URL: "mongodb"
      MODEL_URL: "http://ml-backend:5000"
    ports:
      - "5100:5100"
    volumes:
      - ${LOGDIR}/labeler.log:/home/error.log
      - ${SRVDIR}/data:/home/datasets
    depends_on:
      - mongodb


  flask_sdk:
    build:
      context: backend
      dockerfile: SdkDockerFile
    container_name: mlcheap-sdk
    restart: always
    environment:
      APP_ENV: "prod"
      APP_DEBUG: "False"
      MONGO_URL: "mongodb"
    ports:
      - "6221:6221"
    volumes:
    volumes:
      - ${LOGDIR}/sdk.log:/home/error.log
      - ${SRVDIR}/data:/home/datasets
    depends_on:
      - mongodb


  mongodb:
    image: mongo
    container_name: mlcheap-mongodb
    restart: always
    command: mongod --profile=2 
    environment:
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /data/log
    volumes:
      - ${SRVDIR}/mongodb:/data/db
      - ${LOGDIR}/mongodb.log:/var/log/mongodb/mongodb.log

  web_builder:
    container_name: mlcheap-webbuilder
    build:
      context: webapp
      dockerfile: Dockerfile
    environment:
      APP_ENV: "prod"
      APP_NAME: "webservice"
      APP_DEBUG: "false"
      SERVICE_NAME: "webservice"
      PROXY: "flask_labeler"
      MODEL_URL: "ml-backend:5000"
    volumes:
      - builddata:/build/build
    depends_on:
      - flask_labeler

  ml-backend:
    build:
      context: ml-backend
      dockerfile: Dockerfile
    container_name: mlcheap-ml-backend
    volumes:
      - ${SRVDIR}/ml-backend/models:/home/models
    environment:
      FLASK_APP: app
      FLASK_ENV: development
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 5000
    ports:
      - "5000:5000"
      - "8890:8888"
    depends_on:
      - skillmap
      - vacancies
    restart: always

  dashboard:
    build:
      context: dashboard
      dockerfile: Dockerfile
    container_name: mlcheap-dashboard
    volumes:
      - ${SRVDIR}/dashboard/data:/home/data
    environment:
      FLASK_ENV: development
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 4000
      ML_HOST: "${ML_HOST}"
      SDK_HOST: "${SDK_HOST}"
      SKILL_HOST: "${SKILL_HOST}"
      VAC_HOST: "${VAC_HOST}"
    ports:
      - "4000:4000"
      - "8889:8888"
    depends_on:
      - skillmap
      - vacancies
    restart: always

  ml_deep_learning: 
    container_name: ml_deep_learning
    build:
      context: ml_deep_learning
      dockerfile: Dockerfile
    ports:
      - "6000:80"

  admin: 
    container_name: mlcheap-admin
    build:
      context: admin
      dockerfile: Dockerfile
    volumes:
      - ./admin/src:/app/src

  skillmap:
    container_name: proxy-skillmap
    image: gcr.io/cloudsql-docker/gce-proxy:1.19.1
    command: /cloud_sql_proxy --dir=/cloudsql -instances=skilllab-app:europe-west4:skillmap-pg13-production=tcp:0.0.0.0:5432 -credential_file=/secrets/cloudsql/credentials.json
    ports:
      - "8765:5432"
    volumes:
      - ${SRVDIR}/sql_proxy/credentials.json:/secrets/cloudsql/credentials.json
    restart: always

  vacancies:
    container_name: proxy-vacancies
    image: gcr.io/cloudsql-docker/gce-proxy:1.19.1
    command: /cloud_sql_proxy --dir=/cloudsql -instances=skilllab-app:europe-west4:vacancies-api-prod=tcp:0.0.0.0:5432 -credential_file=/secrets/cloudsql/credentials.json
    ports:
      - "5678:5432"
    volumes:
      - ${SRVDIR}/sql_proxy/credentials.json:/secrets/cloudsql/credentials.json
    restart: always

  httpd:
    build:
      context: httpd
      dockerfile: Dockerfile
    container_name: mlcheap-httpd
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - builddata:/srv/www/webapp
      - ${SRVDIR}/ssl:/srv/ssl
    depends_on:
      - web_builder
 
volumes:
  builddata: 
    driver: local
